

METHODS = [
    # --- DISCOVERY ---
    ("QUERY",         ["discovery", "mechanics"],   "Structured request for matching records or state."),
    ("DISCOVER",      ["discovery", "mechanics"],   "Surface available resources, agents, or capabilities."),
    ("FIND",          ["discovery"],                "Locate an item matching given criteria."),
    ("LOCATE",        ["discovery"],                "Determine the position or address of a known entity."),
    ("SEARCH",        ["discovery"],                "Scan a corpus or index for matches."),
    ("BROWSE",        ["discovery"],                "Traverse a hierarchy or listing without a target."),
    ("EXPLORE",       ["discovery"],                "Open-ended traversal to map an unknown space."),
    ("IDENTIFY",      ["discovery", "analysis"],    "Determine the identity or class of an entity."),
    ("DETECT",        ["discovery", "analysis"],    "Recognize the presence of a signal or condition."),
    ("OBSERVE",       ["discovery", "mechanics"],   "Passively watch state without acting on it."),
    ("MONITOR",       ["discovery"],                "Continuously observe for changes or thresholds."),
    ("TRACK",         ["discovery"],                "Follow an entity's state across time."),
    ("PROBE",         ["discovery"],                "Send a controlled stimulus to elicit a response."),
    ("SCAN",          ["discovery"],                "Systematically inspect a range of items."),
    ("INSPECT",       ["discovery", "analysis"],    "Closely examine an item's structure or contents."),
    ("EXAMINE",       ["discovery", "analysis"],    "Investigate the details of an item."),
    ("INVESTIGATE",   ["discovery"],                "Pursue a question through evidence-gathering."),
    ("SURVEY",        ["discovery"],                "Sample broadly to characterize a population."),
    ("CRAWL",         ["discovery"],                "Recursively traverse linked resources."),
    ("INDEX",         ["discovery"],                "Build a lookup structure over a corpus."),
    ("ENUMERATE",     ["discovery"],                "List every member of a defined set."),
    ("LIST",          ["discovery"],                "Return the members of a collection."),
    ("LOOKUP",        ["discovery"],                "Resolve a key against a known mapping."),
    ("MATCH",         ["discovery", "analysis"],    "Test whether items satisfy a pattern."),
    ("RESOLVE",       ["discovery"],                "Translate a reference to a concrete entity."),
    ("RECOGNIZE",     ["discovery", "analysis"],    "Identify a known pattern within input."),
    ("SENSE",         ["discovery"],                "Acquire a low-level signal from the environment."),
    ("WATCH",         ["discovery"],                "Observe a target for change events."),
    ("TRACE",         ["discovery", "analysis"],    "Follow a chain of causes or references."),
    ("FOLLOW",        ["discovery"],                "Move along a path or feed of items."),
    ("SPOT",          ["discovery"],                "Notice an item of interest among many."),
    ("PINPOINT",      ["discovery"],                "Narrow a location or cause to a precise point."),
    ("UNCOVER",       ["discovery"],                "Reveal something previously hidden or missed."),
    ("REVEAL",        ["discovery"],                "Make a previously hidden value visible."),
    ("EXPOSE",        ["discovery"],                "Make an internal state available externally."),
    ("SAMPLE",        ["discovery", "analysis"],    "Take a representative subset for inspection."),
    ("POLL",          ["discovery"],                "Repeatedly query for state at intervals."),
    ("LISTEN",        ["discovery"],                "Wait for inbound events on a channel."),
    ("PEEK",          ["discovery"],                "Inspect without consuming or committing."),
    ("ASCERTAIN",     ["discovery", "analysis"],    "Establish a fact with confidence."),
    ("DETERMINE",     ["discovery", "analysis"],    "Conclude a value through inquiry."),
    ("INTROSPECT",    ["discovery"],                "Examine internal state of self or another agent."),
    ("ENVISION",      ["discovery"],                "Project a hypothetical state for inspection."),

    # --- RETRIEVAL ---
    ("FETCH",         ["retrieval"],                "Retrieve a resource by identifier or location."),
    ("RETRIEVE",      ["retrieval"],                "Recover a stored item into working context."),
    ("GET",           ["retrieval"],                "Legacy retrieval verb.", "FETCH"),
    ("READ",          ["retrieval"],                "Read content from a source."),
    ("LOAD",          ["retrieval"],                "Bring data into memory or runtime state."),
    ("PULL",          ["retrieval"],                "Initiate transfer from a remote source."),
    ("ACCESS",        ["retrieval"],                "Obtain authorized use of a resource."),
    ("OPEN",          ["retrieval"],                "Establish a handle or session over a resource."),
    ("EXTRACT",       ["retrieval", "analysis"],    "Pull a substructure out of a larger artifact."),
    ("GATHER",        ["retrieval"],                "Collect items from multiple sources."),
    ("COLLECT",       ["retrieval"],                "Aggregate items into a single set."),
    ("OBTAIN",        ["retrieval"],                "Acquire possession or access to an item."),
    ("RECEIVE",       ["retrieval", "domain"], "Accept inbound delivery of an item."),
    ("DOWNLOAD",      ["retrieval"],                "Copy a remote artifact to local storage."),
    ("IMPORT",        ["retrieval"],                "Bring external data into the system."),
    ("INGEST",        ["retrieval"],                "Accept and prepare external input for use."),
    ("HARVEST",       ["retrieval"],                "Systematically collect items from sources."),
    ("SCRAPE",        ["retrieval"],                "Extract data from unstructured surfaces."),
    ("ASSEMBLE",      ["retrieval", "creation"],    "Combine fetched parts into a whole."),
    ("COMPILE",       ["retrieval", "creation"],    "Build a composite from constituent inputs."),
    ("CAPTURE",       ["retrieval"],                "Record a transient signal to durable form."),
    ("ACQUIRE",       ["retrieval"],                "Take ownership or possession of an asset."),
    ("CACHE",         ["retrieval"],                "Store a copy for faster subsequent access."),
    ("PREFETCH",      ["retrieval"],                "Retrieve in advance of expected use."),
    ("STREAM",        ["retrieval", "notification"], "Deliver content in a continuous flow."),
    ("BUFFER",        ["retrieval"],                "Hold incoming data temporarily before use."),
    ("CHECKOUT",      ["retrieval"],                "Acquire an item from shared storage for use."),
    ("CHECKIN",       ["retrieval", "modification"], "Return a checked-out item with updates."),
    ("SNAPSHOT",      ["retrieval"],                "Capture a point-in-time copy of state."),
    ("EXPORT",        ["retrieval"],                "Render and emit data for external use."),
    ("MIRROR",        ["retrieval", "modification"], "Maintain a synchronized copy of a source."),
    ("REPLICATE",     ["retrieval", "creation"],    "Produce a duplicate of an existing artifact."),
    ("DUMP",          ["retrieval"],                "Emit a complete byte-level copy of state."),
    ("ENUMERATE",     ["retrieval", "discovery"],   "List the keys present in a store."),
    ("SUBSCRIBE",     ["retrieval", "notification"],"Open a continuous read against a feed."),

    # --- ANALYSIS ---
    ("ANALYZE",       ["analysis"],                 "Break input into components and assess them."),
    ("EVALUATE",      ["analysis"],                 "Compute the value of an expression or condition."),
    ("ASSESS",        ["analysis"],                 "Form a judgment about quality or risk."),
    ("MEASURE",       ["analysis"],                 "Quantify a property against a unit."),
    ("COMPARE",       ["analysis"],                 "Determine differences between items."),
    ("COMPUTE",       ["analysis"],                 "Produce a result through calculation."),
    ("CALCULATE",     ["analysis"],                 "Apply arithmetic to derive a value."),
    ("CLASSIFY",      ["analysis"],                 "Assign an item to a defined class."),
    ("CATEGORIZE",    ["analysis"],                 "Place an item into a taxonomic group."),
    ("RANK",          ["analysis"],                 "Order items by a criterion."),
    ("SCORE",         ["analysis"],                 "Assign a numeric judgment to an item."),
    ("AUDIT",         ["analysis"],                 "Examine for compliance or correctness."),
    ("RECONCILE",     ["analysis"],                 "Resolve discrepancies between sources."),
    ("VALIDATE",      ["analysis"],                 "Confirm conformance to a specification."),
    ("VERIFY",        ["analysis"],                 "Confirm a claim through evidence."),
    ("CHECK",         ["analysis", "discovery"],    "Test a condition or property."),
    ("REVIEW",        ["analysis"],                 "Examine for quality or approval."),
    ("SUMMARIZE",     ["analysis", "mechanics"],    "Produce a condensed account of input."),
    ("SYNTHESIZE",    ["analysis", "creation"],     "Combine sources into a new coherent whole."),
    ("AGGREGATE",     ["analysis"],                 "Combine multiple values into a summary."),
    ("FILTER",        ["analysis"],                 "Retain items matching a predicate."),
    ("SORT",          ["analysis"],                 "Reorder items by a defined key."),
    ("REDUCE",        ["analysis"],                 "Fold a sequence into a single result."),
    ("TRANSFORM",     ["analysis", "modification"], "Convert input from one form to another."),
    ("CONVERT",       ["analysis", "modification"], "Translate between representations."),
    ("INFER",         ["analysis"],                 "Derive a conclusion from premises."),
    ("DEDUCE",        ["analysis"],                 "Reach a conclusion by formal reasoning."),
    ("DIAGNOSE",      ["analysis"],                 "Identify the cause of an observed condition."),
    ("INTERPRET",     ["analysis"],                 "Assign meaning to ambiguous input."),
    ("JUDGE",         ["analysis"],                 "Render a decision based on criteria."),
    ("ESTIMATE",      ["analysis"],                 "Approximate a value under uncertainty."),
    ("PREDICT",       ["analysis"],                 "Forecast a future value or event."),
    ("FORECAST",      ["analysis"],                 "Project values across a time horizon."),
    ("PROJECT",       ["analysis"],                 "Extend a trend forward in time."),
    ("SIMULATE",      ["analysis"],                 "Run a model to produce hypothetical outcomes."),
    ("MODEL",         ["analysis", "creation"],     "Construct a representation of a system."),
    ("BENCHMARK",     ["analysis"],                 "Measure performance against a reference."),
    ("PROFILE",       ["analysis"],                 "Characterize the behavior of an artifact."),
    ("CORRELATE",     ["analysis"],                 "Find statistical relationships between series."),
    ("CLUSTER",       ["analysis"],                 "Group similar items by inherent structure."),
    ("GROUP",         ["analysis"],                 "Partition items by a chosen attribute."),
    ("BUCKET",        ["analysis"],                 "Place items into discrete bins."),
    ("SEGMENT",       ["analysis"],                 "Divide a population by criteria."),
    ("PARSE",         ["analysis"],                 "Convert serialized input into structured form."),
    ("TOKENIZE",      ["analysis"],                 "Split input into atomic units."),
    ("NORMALIZE",     ["analysis", "modification"], "Bring values to a standard form."),
    ("STANDARDIZE",   ["analysis", "modification"], "Apply a uniform format across items."),
    ("ENCODE",        ["analysis", "modification"], "Convert into an encoded representation."),
    ("DECODE",        ["analysis", "modification"], "Recover content from an encoded form."),
    ("HASH",          ["analysis"],                 "Reduce input to a fixed-size digest."),
    ("CALIBRATE",     ["analysis", "modification"], "Adjust a model to match a reference."),
    ("TUNE",          ["analysis", "modification"], "Adjust parameters for performance."),
    ("OPTIMIZE",      ["analysis", "modification"], "Improve a metric under constraints."),
    ("RATE",          ["analysis"],                 "Assign a qualitative grade."),
    ("GRADE",         ["analysis"],                 "Assign a level of quality or correctness."),
    ("COUNT",         ["analysis"],                 "Determine the cardinality of a set."),
    ("TALLY",         ["analysis"],                 "Accumulate counts across events."),
    ("QUANTIFY",      ["analysis"],                 "Express a property as a number."),
    ("REASON",        ["analysis"],                 "Derive conclusions from available information."),
    ("ABSTRACT",      ["analysis"],                 "Produce a higher-level representation."),
    ("GENERALIZE",    ["analysis"],                 "Extend a pattern beyond observed cases."),
    ("EXTRAPOLATE",   ["analysis"],                 "Project values beyond the known range."),
    ("INTERPOLATE",   ["analysis"],                 "Estimate values between known points."),
    ("APPROXIMATE",   ["analysis"],                 "Produce a close-enough value cheaply."),
    ("PRIORITIZE",    ["analysis"],                 "Order items by importance or urgency."),
    ("FLAG",          ["analysis", "notification"], "Mark an item for attention."),
    ("DISTINGUISH",   ["analysis"],                 "Separate items by identifying differences."),
    ("DIFFERENTIATE", ["analysis"],                 "Articulate distinctions between items."),
    ("RECOMPUTE",     ["analysis"],                 "Recalculate a value after change."),
    ("ANNOTATE",      ["analysis", "modification"], "Attach commentary or metadata to an item."),
    ("ATTRIBUTE",     ["analysis"],                 "Assign provenance or causation to an item."),
    ("DECONSTRUCT",   ["analysis"],                 "Break an artifact into its components."),

    # --- TRANSACTION ---
    ("BOOK",          ["transaction"],              "Reserve a slot or resource."),
    ("RESERVE",       ["transaction"],              "Hold a resource against future use."),
    ("PURCHASE",      ["transaction"],              "Acquire an item by paying for it."),
    ("BUY",           ["transaction"],              "Exchange value for goods or services."),
    ("SELL",          ["transaction"],              "Transfer goods or services for value."),
    ("ORDER",         ["transaction"],              "Submit a request for goods or services."),
    ("REQUEST",       ["transaction", "mechanics"], "Ask another party to perform an action."),
    ("SUBMIT",        ["transaction"],              "Send work or input for processing."),
    ("COMMIT",        ["transaction", "mechanics"], "Finalize a tentative change."),
    ("EXECUTE",       ["transaction", "mechanics"], "Perform a planned action."),
    ("PROCESS",       ["transaction"],              "Apply standard handling to an item."),
    ("TRANSFER",      ["transaction"],              "Move value or ownership between parties."),
    ("EXCHANGE",      ["transaction"],              "Swap items of comparable value."),
    ("TRADE",         ["transaction"],              "Engage in a market exchange."),
    ("PAY",           ["transaction"],              "Render value owed."),
    ("REFUND",        ["transaction"],              "Return previously transferred value."),
    ("REIMBURSE",     ["transaction"],              "Compensate a party for an expense."),
    ("INVOICE",       ["transaction"],              "Issue a request for payment."),
    ("BILL",          ["transaction"],              "Charge a party for goods or services."),
    ("CHARGE",        ["transaction"],              "Apply a debit against an account."),
    ("CREDIT",        ["transaction"],              "Apply a positive entry to an account."),
    ("DEBIT",         ["transaction"],              "Apply a negative entry to an account."),
    ("WITHDRAW",      ["transaction"],              "Remove funds from an account."),
    ("DEPOSIT",       ["transaction"],              "Add funds to an account."),
    ("ALLOCATE",      ["transaction", "domain"],    "Earmark resources for a purpose."),
    ("DEALLOCATE",    ["transaction", "domain"],    "Release earmarked resources."),
    ("ASSIGN",        ["transaction", "domain"],    "Designate a resource to a target."),
    ("REASSIGN",      ["modification", "domain"],   "Change the designation of a resource."),
    ("UNASSIGN",      ["modification", "domain"],   "Remove a resource designation."),
    ("GRANT",         ["transaction", "domain"],    "Confer a right or permission."),
    ("REVOKE",        ["transaction", "domain"],    "Withdraw a previously granted right."),
    ("ISSUE",         ["transaction", "creation"],  "Produce and release an instrument."),
    ("REDEEM",        ["transaction"],              "Exchange an instrument for value."),
    ("SETTLE",        ["transaction"],              "Finalize a payment or trade."),
    ("CLEAR",         ["transaction"],              "Confirm and complete a pending exchange."),
    ("FUND",          ["transaction"],              "Provide capital to a target."),
    ("INVEST",        ["transaction"],              "Allocate capital expecting a return."),
    ("DIVEST",        ["transaction"],              "Withdraw capital from a holding."),
    ("LEND",          ["transaction"],              "Provide an asset under expected return."),
    ("BORROW",        ["transaction"],              "Take an asset under obligation to return."),
    ("LEASE",         ["transaction"],              "Grant temporary use for payment."),
    ("RENT",          ["transaction"],              "Take temporary use for payment."),
    ("HIRE",          ["transaction"],              "Engage a party for paid work."),
    ("SPONSOR",       ["transaction"],              "Underwrite an activity or party."),
    ("APPROVE",       ["transaction"],              "Authorize a pending action."),
    ("REJECT",        ["transaction"],              "Refuse a pending request."),
    ("ACCEPT",        ["transaction"],              "Agree to a presented offer."),
    ("DECLINE",       ["transaction"],              "Refuse a presented offer."),
    ("LICENSE",       ["transaction"],              "Grant conditional use rights."),
    ("SIGN",          ["transaction"],              "Apply an authenticating mark."),
    ("COUNTERSIGN",   ["transaction"],              "Add a confirming signature."),
    ("NOTARIZE",      ["transaction"],              "Attest to a document's authenticity."),
    ("ESCROW",        ["transaction"],              "Hold value pending conditions."),
    ("PLEDGE",        ["transaction"],              "Bind value as collateral or commitment."),
    ("RETIRE",        ["transaction", "modification"], "Permanently remove an instrument from use."),
    ("TENDER",        ["transaction"],              "Offer payment or a bid."),
    ("BID",           ["transaction"],              "Submit a price in an auction."),
    ("AUCTION",       ["transaction"],              "Run a competitive sale process."),
    ("QUOTE",         ["transaction"],              "Provide a price for goods or services."),
    ("PRICE",         ["transaction", "analysis"],  "Determine the value to charge."),
    ("NEGOTIATE",     ["transaction", "mechanics"], "Reach agreement on disputed terms."),
    ("BARGAIN",       ["transaction"],              "Discuss to reach mutually acceptable terms."),
    ("CLOSE",         ["transaction"],              "Finalize a deal or transaction."),
    ("DISBURSE",      ["transaction"],              "Pay out funds from a holding."),
    ("REMIT",         ["transaction"],              "Send payment to a recipient."),
    ("VOID",          ["transaction", "modification"], "Cancel an instrument before settlement."),
    ("CHARGEBACK",    ["transaction"],              "Reverse a posted charge."),
    ("WAIVE",         ["transaction"],              "Forgo a claim or fee."),
    ("UNDERWRITE",    ["transaction"],              "Assume risk for a financial instrument."),
    ("CLAIM",         ["transaction"],              "Assert a right to compensation or benefit."),

    # --- MODIFICATION ---
    ("UPDATE",        ["modification"],             "Replace an existing value with a new one."),
    ("MODIFY",        ["modification"],             "Change one or more attributes of an item."),
    ("REVISE",        ["modification"],             "Produce an improved version of content."),
    ("EDIT",          ["modification"],             "Alter content in place."),
    ("AMEND",         ["modification"],             "Add corrections to an existing record."),
    ("ADJUST",        ["modification"],             "Make small corrective changes."),
    ("ALTER",         ["modification"],             "Change a property of an entity."),
    ("CHANGE",        ["modification"],             "Replace one state with another."),
    ("CONFIGURE",     ["modification"],             "Set parameters that govern behavior."),
    ("SET",           ["modification"],             "Assign a value to a named slot."),
    ("RESET",         ["modification"],             "Restore to a defined initial state."),
    ("RESTORE",       ["modification"],             "Recover a prior state from backup."),
    ("REPAIR",        ["modification"],             "Fix damage to an artifact."),
    ("FIX",           ["modification"],             "Correct an identified defect."),
    ("REFRESH",       ["modification"],             "Reload to incorporate the latest state."),
    ("RENEW",         ["modification", "transaction"], "Extend the validity of an instrument."),
    ("EXTEND",        ["modification"],             "Lengthen the duration or scope of an item."),
    ("UPGRADE",       ["modification"],             "Move to a higher version or tier."),
    ("DOWNGRADE",     ["modification"],             "Move to a lower version or tier."),
    ("MIGRATE",       ["modification"],             "Move data or workload to a new substrate."),
    ("ARCHIVE",       ["modification"],             "Move to long-term inactive storage."),
    ("UNARCHIVE",     ["modification"],             "Restore an archived item to active use."),
    ("DELETE",        ["modification"],             "Legacy removal verb.", "REMOVE"),
    ("REMOVE",        ["modification"],             "Eliminate an item from a collection."),
    ("PURGE",         ["modification"],             "Permanently and unrecoverably delete."),
    ("REDACT",        ["modification"],             "Obscure sensitive content while retaining structure."),
    ("ANONYMIZE",     ["modification"],             "Strip identifying information from records."),
    ("MASK",          ["modification"],             "Hide sensitive values for display."),
    ("OBFUSCATE",     ["modification"],             "Render content harder to interpret."),
    ("ENCRYPT",       ["modification"],             "Render content unreadable without a key."),
    ("DECRYPT",       ["modification"],             "Recover plaintext using a key."),
    ("COMPRESS",      ["modification"],             "Reduce the size of content."),
    ("DECOMPRESS",    ["modification"],             "Restore content to its uncompressed form."),
    ("MERGE",         ["modification"],             "Combine multiple items into one."),
    ("SPLIT",         ["modification"],             "Divide an item into multiple parts."),
    ("JOIN",          ["modification"],             "Combine items by a relationship."),
    ("COMBINE",       ["modification"],             "Bring items together as one."),
    ("APPEND",        ["modification"],             "Add content to the end of an item."),
    ("PREPEND",       ["modification"],             "Add content to the beginning of an item."),
    ("INSERT",        ["modification"],             "Place content at a specified position."),
    ("REPLACE",       ["modification"],             "Substitute new content for old."),
    ("SWAP",          ["modification"],             "Exchange the positions of two items."),
    ("ROTATE",        ["modification"],             "Cycle items through positions."),
    ("REORDER",       ["modification"],             "Change the sequence of items."),
    ("REORGANIZE",    ["modification"],             "Restructure the layout of a collection."),
    ("RESTRUCTURE",   ["modification"],             "Change the shape or schema of an item."),
    ("REFACTOR",      ["modification"],             "Restructure code without changing behavior."),
    ("RENAME",        ["modification"],             "Assign a new identifier to an existing item."),
    ("RELABEL",       ["modification"],             "Change a non-identifying label."),
    ("RETAG",         ["modification"],             "Replace tags on an item."),
    ("ROLLBACK",      ["modification", "mechanics"],"Revert to a prior committed state."),
    ("REVERT",        ["modification"],             "Undo recent changes to a known state."),
    ("UNDO",          ["modification"],             "Reverse the most recent change."),
    ("REDO",          ["modification"],             "Reapply a previously undone change."),
    ("OVERWRITE",     ["modification"],             "Replace existing content without merging."),
    ("OVERRIDE",      ["modification"],             "Supersede a default with a specific value."),
    ("PATCH",         ["modification"],             "Apply a targeted change to an artifact."),
    ("DUPLICATE",     ["modification", "creation"], "Produce a copy of an existing item."),
    ("FORK",          ["modification", "creation"], "Create a divergent copy for separate evolution."),
    ("BRANCH",        ["modification", "creation"], "Create a parallel line of changes."),
    ("TRUNCATE",      ["modification"],             "Cut an item to a shorter length."),
    ("RESIZE",        ["modification"],             "Change the size of a resource."),
    ("RESCHEDULE",    ["modification", "domain"], "Move a planned event to a new time."),
    ("RECONFIGURE",   ["modification", "domain"], "Change configuration of a running system."),
    ("REPATH",        ["modification"],             "Change the location reference of an item."),
    ("REROUTE",       ["modification", "domain"], "Send traffic via a new path."),
    ("REBASE",        ["modification"],             "Replay changes onto a new base state."),

    # --- CREATION ---
    ("CREATE",        ["creation"],                 "Bring a new entity into existence."),
    ("GENERATE",      ["creation"],                 "Produce output from input or parameters."),
    ("COMPOSE",       ["creation"],                 "Build a structured artifact from parts."),
    ("DRAFT",         ["creation"],                 "Produce a preliminary version."),
    ("AUTHOR",        ["creation"],                 "Write original content."),
    ("RENDER",        ["creation"],                 "Produce a presentation form from a model."),
    ("BUILD",         ["creation"],                 "Construct an artifact from sources."),
    ("CONSTRUCT",     ["creation"],                 "Assemble parts into a whole."),
    ("FABRICATE",     ["creation"],                 "Manufacture from raw materials."),
    ("PRODUCE",       ["creation"],                 "Bring forth an output from a process."),
    ("FORGE",         ["creation"],                 "Form an artifact through deliberate work."),
    ("DESIGN",        ["creation"],                 "Specify the form and behavior of an artifact."),
    ("PROTOTYPE",     ["creation"],                 "Build an early working model."),
    ("INSTANTIATE",   ["creation", "mechanics"],    "Create an instance from a definition."),
    ("SPAWN",         ["creation", "mechanics"],    "Initiate a new process or agent."),
    ("DEFINE",        ["creation"],                 "Establish the meaning or shape of a term."),
    ("DECLARE",       ["creation"],                 "State the existence or value of an item."),
    ("ESTABLISH",     ["creation"],                 "Found or set up an entity or rule."),
    ("ORIGINATE",     ["creation"],                 "Bring something into being for the first time."),
    ("FORMULATE",     ["creation"],                 "Express precisely as a definition or plan."),
    ("CRAFT",         ["creation"],                 "Make with deliberate care."),
    ("MINT",          ["creation"],                 "Produce a new instance of an instrument."),
    ("TEMPLATE",      ["creation"],                 "Generate from a parameterized form."),
    ("SCAFFOLD",      ["creation"],                 "Generate baseline structure for an artifact."),
    ("SEED",          ["creation"],                 "Populate initial state for a new entity."),
    ("PROVISION",     ["creation", "domain"], "Bring a new resource into existence and ready it."),

    # --- NOTIFICATION ---
    ("NOTIFY",        ["notification", "mechanics"], "Inform a recipient of an event or fact."),
    ("ALERT",         ["notification"],             "Notify with elevated urgency."),
    ("BROADCAST",     ["notification"],             "Send a message to all recipients."),
    ("ANNOUNCE",      ["notification"],             "Publicly state new information."),
    ("PUBLISH",       ["notification", "mechanics"], "Emit content to subscribers."),
    ("SUBSCRIBE",     ["notification", "mechanics"], "Register interest in a stream of events."),
    ("UNSUBSCRIBE",   ["notification", "mechanics"], "Remove a previously registered interest."),
    ("ACKNOWLEDGE",   ["notification", "mechanics"], "Confirm receipt of a message."),
    ("CONFIRM",       ["notification", "mechanics"], "Affirm a stated fact or intent."),
    ("REPORT",        ["notification"],             "Provide a structured account of state."),
    ("ESCALATE",      ["notification", "mechanics"], "Raise an issue to a higher authority."),
    ("REMIND",        ["notification"],             "Prompt about a previously known item."),
    ("INVITE",        ["notification"],             "Offer participation to a recipient."),
    ("EMIT",          ["notification"],             "Produce an outbound event."),
    ("SIGNAL",        ["notification"],             "Convey a discrete state to listeners."),
    ("PING",          ["notification"],             "Send a minimal liveness probe."),
    ("WARN",          ["notification"],             "Caution about a possible problem."),
    ("ADVISE",        ["notification"],             "Recommend a course of action."),
    ("INFORM",        ["notification"],             "Convey a fact to a recipient."),
    ("MESSAGE",       ["notification"],             "Send a directed communication."),
    ("FORWARD",       ["notification"],             "Relay a message to another recipient."),
    ("RELAY",         ["notification"],             "Pass a signal through an intermediary."),
    ("ECHO",          ["notification"],             "Return a copy of received input."),
    ("RESPOND",       ["notification", "mechanics"], "Reply to a received message."),
    ("REPLY",         ["notification"],             "Send a return message in a thread."),
    ("COMMENT",       ["notification"],             "Attach a remark to an item."),
    ("POST",          ["notification"],             "Publish to a feed or channel."),
    ("GREET",         ["notification"],             "Send an opening salutation."),
    ("PROMPT",        ["notification"],             "Solicit input from a counterparty."),
    ("SOLICIT",       ["notification"],             "Request submissions or input."),
    ("SUMMON",        ["notification"],             "Call a party to attend or respond."),
    ("BEACON",        ["notification"],             "Emit a periodic identification signal."),
    ("DISCLOSE",      ["notification"],             "Reveal information formally."),
    ("ATTRIBUTE",     ["notification", "analysis"], "Publicly assign authorship or cause."),

    # --- MECHANICS (protocol primitives; many also live in other categories) ---
    ("DESCRIBE",      ["mechanics", "discovery"],   "Return a structured self-description."),
    ("PLAN",          ["mechanics", "creation"],    "Produce a sequence of intended actions."),
    ("DELEGATE",      ["mechanics"],                "Assign work to another agent."),
    ("HANDOFF",       ["mechanics"],                "Transfer ownership of a task to another agent."),
    ("PROPOSE",       ["mechanics"],                "Offer a tentative action for review."),
    ("INVOKE",        ["mechanics"],                "Call a named capability or method."),
    ("DISPATCH",      ["mechanics", "domain"], "Route a request to a handler."),
    ("AUTHENTICATE",  ["mechanics", "domain"], "Establish the identity of a party."),
    ("AUTHORIZE",     ["mechanics", "domain"], "Determine permission for an action."),
    ("ATTEST",        ["mechanics"],                "Provide signed evidence of a fact."),
    ("CHALLENGE",     ["mechanics"],                "Require proof from a counterparty."),
    ("ABORT",         ["mechanics"],                "End an operation before completion."),
    ("RETRY",         ["mechanics"],                "Reattempt a failed operation."),
    ("FALLBACK",      ["mechanics"],                "Switch to an alternative when primary fails."),
    ("ROUTE",         ["mechanics", "domain"], "Choose a path for a request or message."),
    ("REGISTER",      ["mechanics", "domain"], "Record presence in a registry."),
    ("DEREGISTER",    ["mechanics", "domain"], "Remove presence from a registry."),
    ("GOVERN",        ["mechanics"],                "Apply policy to constrain an action."),
    ("ENFORCE",       ["mechanics"],                "Compel adherence to a policy."),
    ("PERMIT",        ["mechanics"],                "Allow an action under policy."),
    ("DENY",          ["mechanics"],                "Refuse an action under policy."),
    ("BLOCK",         ["mechanics", "modification"],"Prevent a request from proceeding."),
    ("ALLOW",         ["mechanics"],                "Let a request proceed."),
    ("QUARANTINE",    ["mechanics", "modification"],"Isolate a suspect artifact pending review."),
    ("AUDITLOG",      ["mechanics"],                "Record an action in an immutable log."),
    ("CHECKPOINT",    ["mechanics", "domain"], "Record state for possible later resumption."),
    ("YIELD",         ["mechanics"],                "Voluntarily release control to another party."),
    ("AWAIT",         ["mechanics"],                "Pause until a condition or event."),
    ("HEARTBEAT",     ["mechanics", "notification"],"Periodically signal liveness."),

    # --- DOMAIN-SPANNING (lifecycle / control plane) ---
    ("SCHEDULE",      ["domain"],          "Place an item on a future timeline."),
    ("CANCEL",        ["domain"],          "Withdraw a pending or future action."),
    ("REBOOK",        ["domain"],          "Replace an existing booking with a new one."),
    ("ENROLL",        ["domain", "transaction"], "Register a party in a program."),
    ("ONBOARD",       ["domain"],          "Bring a party into operational readiness."),
    ("OFFBOARD",      ["domain"],          "Remove a party from operational status."),
    ("ACTIVATE",      ["domain"],          "Bring an entity into an operational state."),
    ("DEACTIVATE",    ["domain"],          "Take an entity out of operational state."),
    ("SUSPEND",       ["domain", "mechanics"], "Pause an entity reversibly."),
    ("RESUME",        ["domain", "mechanics"], "Continue a suspended entity."),
    ("PAUSE",         ["domain", "mechanics"], "Temporarily halt an ongoing process."),
    ("START",         ["domain"],          "Begin a process or service."),
    ("STOP",          ["domain"],          "Halt a process or service."),
    ("INITIATE",      ["domain", "mechanics"], "Begin a defined procedure."),
    ("TERMINATE",     ["domain", "mechanics"], "End a process definitively."),
    ("DELIVER",       ["domain"],          "Transfer an item to a recipient."),
    ("SHIP",          ["domain"],          "Send goods to a destination."),
    ("PROVISION",     ["domain"],          "Prepare and allocate a resource for use."),
    ("DEPROVISION",   ["domain"],          "Tear down and release a provisioned resource."),
    ("DEPLOY",        ["domain"],          "Place a build into a runtime environment."),
    ("UNDEPLOY",      ["domain"],          "Remove a build from a runtime environment."),
    ("INSTALL",       ["domain"],          "Set up software for use."),
    ("UNINSTALL",     ["domain"],          "Remove installed software."),
    ("MOUNT",         ["domain"],          "Attach a storage volume to a runtime."),
    ("UNMOUNT",       ["domain"],          "Detach a mounted storage volume."),
    ("ATTACH",        ["domain"],          "Connect a peripheral or accessory to a host."),
    ("DETACH",        ["domain"],          "Disconnect a peripheral from a host."),
    ("BIND",          ["domain"],          "Associate a name with an endpoint."),
    ("UNBIND",        ["domain"],          "Dissociate a name from an endpoint."),
    ("CONNECT",       ["domain"],          "Open a session between parties."),
    ("DISCONNECT",    ["domain"],          "Close a session between parties."),
    ("LINK",          ["domain"],          "Establish a relationship between items."),
    ("UNLINK",        ["domain"],          "Remove a relationship between items."),
    ("PAIR",          ["domain"],          "Form a trusted association between devices."),
    ("UNPAIR",        ["domain"],          "Dissolve a trusted device association."),
    ("ENABLE",        ["domain"],          "Turn on a feature or capability."),
    ("DISABLE",       ["domain"],          "Turn off a feature or capability."),
    ("RESTART",       ["domain"],          "Stop and immediately start a service."),
    ("REBOOT",        ["domain"],          "Restart a host system."),
    ("SHUTDOWN",      ["domain"],          "Bring a system to an off state in order."),
    ("BOOTSTRAP",     ["domain"],          "Initialize a system from minimal inputs."),
    ("COMMISSION",    ["domain"],          "Place into operational service."),
    ("DECOMMISSION",  ["domain"],          "Retire from operational service."),
    ("EXPIRE",        ["domain"],          "Mark an item as past validity."),
    ("RENEW",         ["domain"],        "Extend lifecycle validity through formal action."),
    ("FAILOVER",      ["domain", "mechanics"], "Switch to a standby on primary failure."),
    ("FAILBACK",      ["domain", "mechanics"], "Return to primary after recovery."),
    ("RECOVER",       ["domain"],          "Restore service after a failure."),
    ("RECONCILE",     ["domain", "analysis"], "Bring observed state to match desired."),
    ("DRAIN",         ["domain"],          "Bleed traffic off a node before stop."),
    ("CORDON",        ["domain"],          "Block new work on a node without stopping it."),
    ("UNCORDON",      ["domain"],          "Restore acceptance of new work on a node."),
    ("EVICT",         ["domain"],          "Forcibly remove a workload from a host."),
    ("PROMOTE",       ["domain"],          "Advance an artifact to a higher environment."),
    ("DEMOTE",        ["domain"],          "Move an artifact to a lower environment."),
    ("ROLLOUT",       ["domain"],          "Progressively deliver a change."),
    ("ROLLBACK",      ["domain"],        "Revert a release to a prior version."),
    ("CUTOVER",       ["domain"],          "Switch traffic from old system to new."),
]

